### ISSUE TITLE
Organize projects page better

### ISSUE THREAD

**Issue by rufuspollock** [okfn/okfn.github.com#46]
## Plan

These are the things we plan to do
- [x] #161 - add attributes to projects (see below)
- [x] #160  new style layout
- [x] #160  - Filtering by those attributes
- [x] #162 - individual project lightbox
- [x] instructions for "Add a project to this list" - @andylolz 
- [x] Have someone as project meister - @andylolz 
### Project attributes
- `featured`: yes/no
- `helpwanted`: yes/no
  - documentation should be in the project page
- `typeofhelp`:
  - coding
  - data analysis
  - data wrangling
  - testing
  - documenting
  - blogging
  - evangelism (talking at events etc)
  - project managing
- `language`: js, python, ...
- `type`: (data) tool, visualization, webapp, library, service (webservice)
- `status`: one of [alpha, prototype, live, mature]

---
## Context

Project list is rather overwhelming at the moment (and will get more so over time).

How could we organize better? First lets think of the purpose:
1. Make it easy for people to find projects that people can get involved with or contribute to
   - Ideally these are projects that combine
     - a genuine need
     - **ease of contribution** (i.e. you don't need to install a hugely complicated system just to do a patch) - cf ideas "Simple" tag
   - Skills info (no good working on a python project if i'm js person)
   - Possibly by type: cf the [ideas list](https://github.com/okfn/ideas/issues) which has:
     - Tools & Libraries
     - Apps & Services
     - Investigation & Visualization
     - Research
2. Make it easy to find projects people can use
3. Provide a showcase
   - nice mix of tools, libraries, apps, services etc
4. Provide a space where labs members (contributors) can list their projects/activities
## User Stories

(in progress)

As a **civic hacker** newly arrived on labs I want to see what kind of work you do so that I have an idea whether this is the kind of **place I want to hangout**

As a **civic hacker** newly arrived on labs I want to see what kind of work you do so that I can get a sense of whether there is a **project I could contribute to**

As a civic hacker newly arrived on labs I want to see what kind of work you do so that I can get a sense of whether there is a **project I could use**

Comments:
- Are there more?
- We could repeat these 3 replacing civic hacker with data wrangler ... (and what other personas we have)
- Which of these 3 is most important
- In all cases I think it will be key to pick a relatively small set of key projects to give an overview and then allow for more investigation
